// Stage 6 — publish.
//
// Audio and artwork go to Cloudflare R2 (zero egress fees, which is the entire
// reason this isn't S3), plus a per-week manifest. The feed itself is served by
// the site from those manifests rather than written here as a static file —
// that's what lets episodes appear one per morning instead of all five landing
// on Sunday night.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { basename, join } from 'node:path';
import { put, putFile } from './r2.mjs';
import { getShow, BRAND } from '../config/show.mjs';
import { currentWeek, currentShow, weekDir, readJSON, writeJSON, need, step, ok, warn, log, fmtDuration, isMain } from './lib.mjs';

const MIME = { '.mp3': 'audio/mpeg', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.png': 'image/png', '.json': 'application/json' };

// Episodes drop one per weekday morning at 5:30am local — before the drive,
// after the phone has had all night to sync on wifi.
// When an episode goes live. Explicitly UTC — the Z matters.
//
// Without it this parsed as LOCAL time, so the air time depended on which
// machine published: 05:30 UTC from a CI runner, 09:30 from a laptop in
// Eastern, 12:30 from one in Pacific. The week of 2026-08-17 shipped at 12:30
// UTC for exactly that reason, and since the feed rebuilds at 09:20 UTC each
// weekday morning, that day's episode would not have been due yet — every
// drive would have got the previous day's episode, for ever.
//
// 09:00 UTC, which satisfies two constraints at once.
//
// It stays before the 09:20 feed refresh, so the drip works even though the
// gate now compares calendar days rather than instants — belt and braces if
// that ever changes back.
//
// And it reads as the correct local day year-round. The house is in Pacific:
// 09:00 UTC is 2am Monday in summer and 1am Monday in winter. The previous
// 07:00 UTC was midnight in summer but ELEVEN PM SUNDAY once the clocks went
// back, so from November onward every episode would have displayed under the
// day before the one it belongs to.
export function airDate(week, part) {
  const d = new Date(`${week}T09:00:00Z`);
  d.setUTCDate(d.getUTCDate() + (part - 1));
  return d;
}

export async function publishWeek(showId, week, { dryRun = false } = {}) {
  const show = getShow(showId);
  const dir = weekDir(showId, week);
  const built = readJSON(join(dir, 'episodes.json'));
  if (!built) throw new Error(`No episodes.json for ${showId} ${week} — run: npm run assemble ${showId} ${week}`);
  const art = readJSON(join(dir, 'art.json'));
  const sources = readJSON(join(dir, 'sources.json'));

  const items = [];
  for (const ep of built.episodes) {
    step(`Publishing ${ep.day} — ${ep.title}`);
    const audioKey = `audio/${showId}/${week}/part${ep.part}.mp3`;
    const artKey = `art/${showId}/${week}/part${ep.part}.jpg`;
    const artFile = art?.episodes.find((a) => a.part === ep.part)?.file;

    let audioUrl, artUrl;
    if (dryRun) {
      const base = (process.env.R2_PUBLIC_BASE || 'https://media.example').replace(/\/$/, '');
      audioUrl = `${base}/${audioKey}`;
      artUrl = artFile ? `${base}/${artKey}` : null;
      log(`  (dry run) ${audioKey}  ${(ep.bytes / 1e6).toFixed(1)} MB`);
    } else {
      audioUrl = await putFile(audioKey, ep.file, 'audio/mpeg');
      artUrl = artFile && existsSync(artFile) ? await putFile(artKey, artFile, 'image/jpeg') : null;
      ok(`${(ep.bytes / 1e6).toFixed(1)} MB → ${audioKey}`);
    }

    items.push({
      guid: `${showId}-${week}-part${ep.part}`,
      part: ep.part,
      day: ep.day,
      title: ep.title,
      teaser: ep.teaser,
      pubDate: airDate(week, ep.part).toUTCString(),
      pubDateISO: airDate(week, ep.part).toISOString(),
      audioUrl,
      artUrl,
      bytes: ep.bytes,
      seconds: Math.round(ep.seconds),
      duration: fmtDuration(ep.seconds),
      chapters: ep.chapters,
      // Show notes carry the sources so a claim is always one tap from its page,
      // plus the Unsplash credit the API terms require.
      notes: buildNotes(ep, sources, art),
    });
  }

  const manifest = { show: showId, week, title: show.title, published_at: new Date().toISOString(), episodes: items };
  writeJSON(join(dir, 'manifest.json'), manifest);

  if (!dryRun) {
    await put(`manifest/${showId}/${week}.json`, JSON.stringify(manifest), 'application/json', { immutable: false });
    ok(`manifest → manifest/${showId}/${week}.json`);
  }

  // A static copy is handy for validating against Apple's requirements even
  // though the live feed is generated by the site.
  const xml = buildFeed(showId, [manifest], { all: true });
  writeFileSync(join(dir, 'feed-preview.xml'), xml);
  ok(`feed preview → ${join(dir, 'feed-preview.xml')}`);

  return manifest;
}

function buildNotes(ep, sources, art) {
  const lines = [ep.teaser, ''];
  if (ep.chapters?.length) {
    lines.push('Chapters:');
    for (const c of ep.chapters) lines.push(`  ${fmtDuration(c.start)} — ${c.label}`);
    lines.push('');
  }
  const used = ep.script?.segments?.flatMap((s) => s.claim_ids) ?? [];
  const urls = [...new Set(
    (sources?.claims ?? []).filter((c) => used.includes(c.id)).map((c) => c.source_url),
  )];
  if (urls.length) {
    lines.push('Sources for this episode:');
    for (const u of urls) lines.push(`  ${u}`);
    lines.push('');
  }
  if (art?.credit_line) lines.push(art.credit_line);
  return lines.join('\n').trim();
}

const esc = (s = '') => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

export function buildFeed(showId, manifests, { all = false, now = new Date(), coverUrl = '' } = {}) {
  const show = getShow(showId);
  const every = manifests
    .flatMap((m) => m.episodes.map((e) => ({ ...e, week: m.week })))
    .sort((a, b) => new Date(b.pubDateISO) - new Date(a.pubDateISO));

  // Gate on the calendar day rather than the instant. An episode is due if its
  // air DATE has arrived, not if its air time has passed — otherwise the whole
  // drip hangs on the cron firing after a specific minute, and a scheduled job
  // running twenty minutes late silently costs a listener that morning's
  // episode. Dates in UTC on both sides, so this can't drift by timezone.
  const today = now.toISOString().slice(0, 10);
  let eps = all ? every : every.filter((e) => e.pubDateISO.slice(0, 10) <= today);

  // A feed with no items is not a feed. Podcast apps reject it outright —
  // Overcast answers "No audio podcast episodes" and refuses to subscribe — so
  // before the first episode airs there is nothing to subscribe to and no way
  // to get ready for Monday. When the date gate empties the feed, release the
  // next episode due rather than nothing.
  //
  // Its pubDate has to move to now as well, which is the part that was missing.
  // An item dated in the future is not "published early", it is *scheduled*:
  // Apple counts it as unavailable, sees a feed with zero episodes and refuses
  // the whole submission with a bare "An error has occurred." Overcast was
  // happy to show it, which is exactly why this survived. If we are choosing to
  // hand someone this episode today then today is when it was published.
  if (!eps.length && every.length) {
    const next = every[every.length - 1];
    eps = [{ ...next, pubDate: now.toUTCString(), pubDateISO: now.toISOString() }];
  }

  const base = (process.env.R2_PUBLIC_BASE || '').replace(/\/$/, '');
  const cover = coverUrl || `${base}/art/cover-${showId}.jpg`;

  // The feed's own canonical address. Apple and most validators want it, and
  // it matters more than usual for this show: it is the record of where the
  // feed is meant to live, which is exactly the thing that gets confusing when
  // the audio host changes.
  const self = `${base}/feed/${process.env.FEED_TOKEN || ''}/${showId}.xml`;

  // Set OLD_FEED_URL when the feed moves house. Apple follows this permanently
  // and existing subscribers come with it; without it they simply stop
  // receiving episodes and never find out why. Leave it set for a couple of
  // weeks after a move, then remove it.
  const moved = process.env.OLD_FEED_URL
    ? `\n    <itunes:new-feed-url>${esc(self)}</itunes:new-feed-url>`
    : '';

  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"
     xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd"
     xmlns:content="http://purl.org/rss/1.0/modules/content/"
     xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>${esc(show.title)}</title>
    <link>${esc(BRAND.siteUrl)}</link>
    <atom:link href="${esc(self)}" rel="self" type="application/rss+xml"/>
    <language>${BRAND.language}</language>
    <description>${esc(show.description)}</description>
    <itunes:author>${esc(BRAND.author)}</itunes:author>
    <itunes:summary>${esc(show.description)}</itunes:summary>
    <itunes:subtitle>${esc(show.tagline)}</itunes:subtitle>
    <itunes:type>episodic</itunes:type>
    <itunes:explicit>${BRAND.explicit ? 'true' : 'false'}</itunes:explicit>
    <itunes:image href="${esc(cover)}"/>
    <itunes:category text="${esc(BRAND.category)}">
      <itunes:category text="${esc(BRAND.subcategory)}"/>
    </itunes:category>
    <itunes:owner>
      <itunes:name>${esc(BRAND.author)}</itunes:name>
      <itunes:email>${esc(process.env.OWNER_EMAIL || '')}</itunes:email>
    </itunes:owner>
${BRAND.listed ? '' : '    <itunes:block>Yes</itunes:block>\n'}${moved ? `${moved.trim()}\n` : ''}${eps.map((e) => `    <item>
      <title>${esc(e.title)}</title>
      <guid isPermaLink="false">${esc(e.guid)}</guid>
      <pubDate>${e.pubDate}</pubDate>
      <description>${esc(e.notes)}</description>
      <content:encoded><![CDATA[${e.notes.replace(/]]>/g, ']]&gt;')}]]></content:encoded>
      <enclosure url="${esc(e.audioUrl)}" length="${e.bytes}" type="audio/mpeg"/>
      <itunes:duration>${e.duration}</itunes:duration>
      <itunes:episode>${e.part}</itunes:episode>
      <itunes:explicit>false</itunes:explicit>${e.artUrl ? `
      <itunes:image href="${esc(e.artUrl)}"/>` : ''}
    </item>`).join('\n')}
  </channel>
</rss>
`;
}

if (isMain(import.meta.url)) {
  const dryRun = process.argv.includes('--dry-run');
  publishWeek(currentShow(), currentWeek(), { dryRun }).catch((e) => {
    console.error(`\n\x1b[31m✖ ${e.message}\x1b[0m`);
    process.exit(1);
  });
}
